# Generated by Django 4.2.3 on 2026-01-09 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nik', models.CharField(max_length=20, unique=True, verbose_name='NIK/NIS')),
                ('kelas', models.CharField(max_length=20)),
                ('no_telepon', models.CharField(max_length=15)),
                ('rfid_uid', models.CharField(max_length=50, unique=True, verbose_name='RFID UID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('hari', models.CharField(blank=True, max_length=20)),
                ('jam_masuk', models.TimeField(auto_now_add=True)),
                ('jam_keluar', models.TimeField(blank=True, null=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absensi_siswa', to='userapp.siswa')),
            ],
        ),
    ]
