# Generated by Django 4.2.27 on 2026-01-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_absensi_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RfidLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_uid', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Berhasil'), ('unknown', 'Tidak Dikenal')], max_length=20)),
                ('keterangan', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
