# Generated by Django 4.2.27 on 2026-01-09 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_rfidlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Data Kelas',
            },
        ),
        migrations.AlterField(
            model_name='siswa',
            name='rfid_uid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='RFID UID'),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='kelas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siswa_list', to='userapp.kelas'),
        ),
    ]
