# Generated by Django 4.2.27 on 2026-01-09 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_kelas_alter_siswa_rfid_uid_alter_siswa_kelas'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaktuOperasional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jam_masuk_mulai', models.TimeField(default=datetime.time(6, 0))),
                ('jam_masuk_akhir', models.TimeField(default=datetime.time(8, 0))),
                ('jam_pulang_mulai', models.TimeField(default=datetime.time(12, 0))),
                ('jam_pulang_akhir', models.TimeField(default=datetime.time(17, 0))),
            ],
            options={
                'verbose_name_plural': 'Waktu Operasional',
            },
        ),
        migrations.AlterModelOptions(
            name='kelas',
            options={},
        ),
    ]
