# Generated by Django 4.2.27 on 2026-01-11 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_waktuoperasional_alter_kelas_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensi',
            name='status_kehadiran',
            field=models.CharField(blank=True, default='Hadir', max_length=50, verbose_name='Status Kehadiran'),
        ),
        migrations.AddField(
            model_name='kelas',
            name='jadwal_masuk_akhir',
            field=models.TimeField(default=datetime.time(7, 15), verbose_name='Batas Terlambat Masuk'),
        ),
        migrations.AddField(
            model_name='kelas',
            name='jadwal_masuk_mulai',
            field=models.TimeField(default=datetime.time(6, 0), verbose_name='Mulai Absen Masuk'),
        ),
        migrations.AddField(
            model_name='kelas',
            name='jadwal_pulang_akhir',
            field=models.TimeField(default=datetime.time(17, 0), verbose_name='Batas Absen Pulang'),
        ),
        migrations.AddField(
            model_name='kelas',
            name='jadwal_pulang_mulai',
            field=models.TimeField(default=datetime.time(14, 0), verbose_name='Mulai Absen Pulang'),
        ),
    ]
