# Generated by Django 4.2.27 on 2026-01-14 04:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_absensi_status_kehadiran_kelas_jadwal_masuk_akhir_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalSesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sesi', models.CharField(max_length=50)),
                ('jam_masuk_mulai', models.TimeField(default=datetime.time(6, 0), verbose_name='Mulai Absen Masuk')),
                ('jam_masuk_akhir', models.TimeField(default=datetime.time(7, 15), verbose_name='Batas Terlambat Masuk')),
                ('jam_pulang_mulai', models.TimeField(default=datetime.time(14, 0), verbose_name='Mulai Absen Pulang')),
                ('jam_pulang_akhir', models.TimeField(default=datetime.time(17, 0), verbose_name='Batas Absen Pulang')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesi_jadwal', to='userapp.kelas')),
            ],
        ),
        migrations.AddField(
            model_name='absensi',
            name='sesi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absensi_sesi', to='userapp.jadwalsesi'),
        ),
    ]
